// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK4gxiljBHTCkG6OJIoah-j5EwtJt-y5E',
    appId: '1:774648478156:web:4b8d31244d0249a0220569',
    messagingSenderId: '774648478156',
    projectId: 'monarch-of-shadows',
    authDomain: 'monarch-of-shadows.firebaseapp.com',
    databaseURL: 'https://monarch-of-shadows-default-rtdb.firebaseio.com',
    storageBucket: 'monarch-of-shadows.firebasestorage.app',
    measurementId: 'G-9JFXHRB3SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5I_NB_mnx8Adjeft4YktjBdFqL_6cBw',
    appId: '1:774648478156:android:4fbb1056fdcea778220569',
    messagingSenderId: '774648478156',
    projectId: 'monarch-of-shadows',
    databaseURL: 'https://monarch-of-shadows-default-rtdb.firebaseio.com',
    storageBucket: 'monarch-of-shadows.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy3q6zUesExqFd1chQjzrdI4U1_7M4_tM',
    appId: '1:774648478156:ios:8029963db24621b5220569',
    messagingSenderId: '774648478156',
    projectId: 'monarch-of-shadows',
    databaseURL: 'https://monarch-of-shadows-default-rtdb.firebaseio.com',
    storageBucket: 'monarch-of-shadows.firebasestorage.app',
    iosBundleId: 'com.example.monarchOfShadows',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy3q6zUesExqFd1chQjzrdI4U1_7M4_tM',
    appId: '1:774648478156:ios:8029963db24621b5220569',
    messagingSenderId: '774648478156',
    projectId: 'monarch-of-shadows',
    databaseURL: 'https://monarch-of-shadows-default-rtdb.firebaseio.com',
    storageBucket: 'monarch-of-shadows.firebasestorage.app',
    iosBundleId: 'com.example.monarchOfShadows',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK4gxiljBHTCkG6OJIoah-j5EwtJt-y5E',
    appId: '1:774648478156:web:a57acf0f63c7829b220569',
    messagingSenderId: '774648478156',
    projectId: 'monarch-of-shadows',
    authDomain: 'monarch-of-shadows.firebaseapp.com',
    databaseURL: 'https://monarch-of-shadows-default-rtdb.firebaseio.com',
    storageBucket: 'monarch-of-shadows.firebasestorage.app',
    measurementId: 'G-JXJZPS8K7J',
  );
}
